/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class PlayerProfile {
    
    constructor(playerId, color, name) { 
        
        PlayerProfile.initialize(this, playerId, color, name);
    }

    
    static initialize(obj, playerId, color, name) { 
        obj['player_id'] = playerId;
        obj['color'] = color;
        obj['name'] = name;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlayerProfile();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], Object);
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], Object);
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlayerProfile.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PlayerProfile.RequiredProperties = ["player_id", "color", "name"];


PlayerProfile.prototype['player_id'] = undefined;


PlayerProfile.prototype['color'] = undefined;


PlayerProfile.prototype['name'] = undefined;






export default PlayerProfile;

